version: "3.9"

services:
  # Django service
  c2s:
    build:
      context: .
      dockerfile: django/Dockerfile
    entrypoint :  
      - /bin/sh
      - /c2s/django/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    # Add any additional configuration you may need for your Django service

  # PostgreSQL service
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    env_file:
      - .env
    # Add any additional configuration you may need for your PostgreSQL service

